# Generated by Django 4.0 on 2021-12-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_color_name_alter_color_color_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_list',
            field=models.CharField(max_length=100000),
        ),
    ]
